name: ffmpeg-2204
summary: ffmpeg content snap for core22
description: FFmpeg is a collection of libraries and tools to process multimedia content such as audio, video, subtitles and related metadata.
version: '6.0'
base: core22
grade: stable
confinement: strict
compression: lzo


lint:
  ignore:
    - classic
    - library:
      - usr/lib/*
      - usr/bin/*
slots:
  ffmpeg-2204:
    interface: content
    read:
      - /

parts:
  ffmpeg-2204:
    plugin: nil
    stage-snaps:
      - ffmpeg-2204-sdk/latest/stable
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/libzimg.a
      - -usr/lib/*/libzimg.la
      - -meta*
      - -snap*
