name: ffmpeg-2404
title: FFmpeg Library Content Snap
summary: ffmpeg content snap for core24
description: |
  FFmpeg is a collection of libraries and tools to process multimedia content such as audio, video, subtitles and related metadata.
  This snap is meant to be consumed with the gnome extension.
version: '7.1'
base: core24
grade: stable
confinement: strict
compression: lzo
license: MIT
contact: soumyadeepghosh2004+ffmpeg@zohomail.in
source-code:
  - https://github.com/FFmpeg/FFmpeg
  - https://git.ffmpeg.org/ffmpeg.git
  - https://github.com/snapcrafters/ffmpeg-sdk
website:
  - https://snapcrafters.org/
issues: https://github.com/snapcrafters/ffmpeg-sdk/issues
lint:
  ignore:
    - classic
    - library
platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
slots:
  ffmpeg-2404:
    interface: content
    read:
      - /
parts:
  ffmpeg-2404:
    plugin: nil
    stage-snaps:
      - ffmpeg-2404-sdk/latest/candidate
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/libzimg.a
      - -usr/lib/*/libzimg.la
      - -meta*
      - -snap*
