name: Promote to stable

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  promote-content:
    name: ⬆️ Promote Content to stable
    environment: "2404 Branch"
    runs-on: ubuntu-latest
    if: |
      ( !github.event.issue.pull_request )
      && contains(github.event.comment.body, '/promote ')
      && contains(github.event.issue.body, '`ffmpeg-2404`')
      && contains(github.event.*.labels.*.name, 'testing')
    steps:
      - name: ⬆️ Promote to stable
        uses: snapcrafters/ci/promote-to-stable@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          store-token: ${{ secrets.SNAP_STORE_STABLE }}
          snapcraft-project-root: "ffmpeg-2404"

  promote-sdk:
    name: ⬆️ Promote SDK to stable
    environment: "2404 Branch"
    runs-on: ubuntu-latest
    if: |
      ( !github.event.issue.pull_request )
      && contains(github.event.comment.body, '/promote ')
      && contains(github.event.issue.body, '`ffmpeg-2404-sdk`')
      && contains(github.event.*.labels.*.name, 'testing')
    steps:
      - name: ⬆️ Promote to stable
        uses: snapcrafters/ci/promote-to-stable@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          store-token: ${{ secrets.SNAP_STORE_STABLE }}
          snapcraft-project-root: "ffmpeg-2404-sdk"
